#! /bin/zsh
# alias
alias "airport=/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport"
alias "detach=tmux detach"
alias "cd=pushd"
alias "dirs=dirs -v"
alias jpm="jpm -b /Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox-bin $1"
